language: go
go:
- 1.12
os:
- linux
script:
- make release
deploy:  
skip_cleanup: true
  provider: releases
  api_key:
    secure: SNo/fbQ+LpXZ2w1ddlpH3VTvuMo9HeKf+iFc1in9H1Yg4/990CdSPnsJclIs7c7AZkOurJnZycrW7MSuq5brfkFqHIhu/fWaRXLQo4P5WF3aKz7BnIVasgGCb051S0YKiHOD/LiUz64FqTF0p+NycEp5r/aDpxjyndWLLplZVlxTniETfbcRnH2VQKe6MDKFVGpURvZJiW2OgxVfe3utHJ9U95yeUbANEyiXz/8Vik+4xPm9y+uCnjqaWd7DPHbAWZNvLn9adV+FxoS1kSVOzSScwJ2yL68lmrF2ddR0qpO4gtraX4DQJyuSQUuFSjJ7uV1iFBgBvrziabpRGXq2SXqyhsqzBxYK9X3rWgLmjzSJprvKXnbcNLrMIgTZk/kw7iaGgpR2EcnOaQVPmHQsiiUJy1nn3TarV3KxxxHAnwmxtJFlBMK39vjrYyVCzLjeJicECCRyXigepOqEijZKa+FuY3gXXCf6/CHGThtE/vHDwB+/90FaBiOGS/LPvgMWS7yfnfS6jCcjtOZgZTTq+/HoGVus1wb9saImrBlf8UKwCnObyynaAzN27edtzdICGOcI7O4rLG84/K2XEAHoKCNcQ0Be5vI5QGuIqsVk3Gk6PNDzf+6INVcp2EI9Jqr4ep5V1N1yoPbG5udPfWahdoYxYuTYp2ul4gVea/xBUzg=
  file_glob: true
  file: output/terraform-provider-git*.zip
  on:
    tags: true
    repo: fourplusone/terraform-provider-git